name: Run the hsa bot

on:
  # schedule:
  #   - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  Running:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot aiohttp pytz translators transformers

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN_HSA }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python hsa/hsa_v2.py